### ISSUE TITLE
Add MatPortal client

### ISSUE THREAD

**Issue by cmungall** [cthoyt/ontoportal-client#2]
MatPortal: 
https://matportal.org/

I would be happy to contribute a PR, but I'd expect to find the API exposed here:
http://data.matportal.org/

Do you know where it is @graybeal?

**Comment by graybeal** [comment]
yes I do, in fact for all of them:
MatPortal API is http://rest.matportal.org/
Agroportal API is:  http://data.agroportal.lirmm.fr/
SIFR Bioportal API is : ​​http://data.bioportal.lirmm.fr/
EcoPortal endpoint: http://ecoportal.lifewatch.eu:8080/
MedPortal endpoint: http://data.medportal.bmicc.cn/
